function [fitresult, xData, yData, gof] = fitPowerLaw(x, y)
%CREATEFIT(S21,V21)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Aug-2019 17:01:05

if numel(x) <= 1
    fitresult.b = nan;
    xData = x;
    yData = y;
    gof = struct();
    return
end


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares',  'Lower', [0, -10] );
opts.Display = 'Off';
%opts.StartPoint = [0.0902089522168906 0.000276577088656382 -2.77226238631911e-10];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




